<!DOCTYPE html>
<html lang="en">
<head>
  <title>Privacy Policy of Pokersportsleague.com</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Know the Privacy policy of PokerSportsleague.com">
  <meta name="keywords" content="Privacy policy of Pokersportsleague, Important privacy rules of PSL">
  <meta name="google-site-verification" content="vjCj63SGzZo9VFaYBFFn3TWRTrkxfjhe71MmxBB1HCc" /> 
  <link rel="icon" type="image/png" sizes="32x32" href="<?php echo IMAGES_PATH?>/favicon-32x32.png">
  <link rel="stylesheet" href="<?php echo CSS_PATH?>/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="<?php echo CSS_PATH?>/owl.carousel.min.css">
  <link rel="stylesheet" href="<?php echo CSS_PATH?>/jquery-ui.css">
  <link rel="stylesheet" href="<?php echo CSS_PATH?>/style.css">
   <link rel="stylesheet" href="css/style.css">
</head>
<body>
<?php $this->load->view('header');?>
<section class="subPagebanner">
<div class="">
<div class="item">
    <div id="loginBanner1" class="imgSlider">
    <div class="container spclftAlgn">
      <div class="bannerMidSec">
          <h2>Privacy Policy</h2>
    </div>
    </div>
    </div>
  </div>
</div>
  </section>
<section class="tnc">
  <div class="container">
    <div class="row">
    <div class="col-xs-12">
      <p>This document is an electronic record in terms of information technology act and rules issued there under  as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the information technology act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
      <p>This document is published by mind sports league private limited (hereinafter referred to as the “company”),  in accordance with the provisions of of the information technology act and rules issued thereunder that require publishing privacy policy for access and usage of www.pokersportsleague.com (hereinafter referred to as the “site” Or “website”). </p>
      <p>This privacy policy  is a legally binding document between you and company. The terms of this privacy policy will be effective upon your acceptance of the same (directly or indirectly in electronic form, by clicking on the "I accept" Tab or by use or the website or by other means) and will govern the relations between you and the company </p>
      <p>Kindly read the policy and all the terms carefully. The present terms shall be read in conjunction with terms of use. The use of this site or your provision to submit any personal information constitutes your unconditional acceptance /consent to the company as required under section 43a or 72a of the information technology act. You further grant your consent for collection, storage, processing and transfer of any or all of your personal and non-personal information including any sensitive personal information as specified under this document.</p>
      <p>If you do not agree with all the terms or have any objection to granting your consent as stated hereinabove, kindly do not browse or use the site/app.</p>
    </div>
      <div class="col-xs-12">
          <h4 class="globleHeadingh4 globlegreen">1. Privacy Notice</h4>
          <p>The Company respects your privacy and thus assures you that any information provided by you to the Company is protected and will be dealt with according to this Policy. The Company shall not provide, distribute, trade, sell or rent your name, e-mail address or other personal information provided on this site to any third party or information related to your usage of the Website, except as provided in this Privacy Policy. The present Document shall inform you of the kinds of information which may be collected by the Company through the Site, the purpose of collecting the same, and the Policy for sharing the Data/Information. The Company shall use the information obtained from you sensibly and carefully.</p>
      </div>
      <div class="col-xs-12">
          <h4 class="globleHeadingh4 globlegreen">2. Information Gathered</h4>
          <p><strong>A. Personal Information -</strong> The Site collects certain personal information including your Username, Password, Name, Date of Birth, Telephone number, Postal/Contact address and a Valid Email address. Additionally, for those of you who have made it to the drafting stage of Poker Sports League, they will need to provide a PAN number.</p>
          <p><strong>B. Non-Personal Information -</strong> The Company also collects non-personal information – data in a form that does not permit direct association /identification with any specific individual, including such as IP addresses, usage details, identifying technologies browser type and language, the date and the time during which you accessed the Site, the address of the website which you may have used to link to the Website.</p>
          <p><strong>C. Sensitive Personal Information -</strong> Whilst the Site does not directly collect or store any Sensitive Personal Data such as financial information including credit card /debit card details, however, such information may be required to be provided to the payment gateway service providers for the purpose of undertaking a transaction on the Site. The terms of the privacy for such Sensitive Personal Information shall be governed by third party service provider and the Company shall not be responsible or liable with respect to its use.</p>
      </div>
      <div class="col-xs-12">
          <h4 class="globleHeadingh4 globlegreen">3. Manner of Collection.</h4>
          <p><strong>A.</strong> Personal and non-personal information may be collected when the user browses the Website, submits information on the Website, enters into a transaction and/or further seeks provision of the services from the Company. The Company may also access information, including personal information, from social media or communication services, commercial sources/databases, services providers or advertisers and other business or commercial associates of the Company.</p>
          <p><strong>B. Normal Browsing -</strong> When you browse, read, submit or download information from the Site, data is collected by the Site, including but not limited to your IP address, URL request, browser type, location and date and time of your actions and web pages visited. </p>
          <p><strong>C. Information You Provide -</strong> The Site requests personally identifiable information when you seek to create an Account on the Site or seek to avail certain specific services on the Site. This information may include, but is not limited to, your name, postal address, location delivery address, telephone number, mobile number and e-mail address.</p>
      </div>
      <div class="col-xs-12">
          <h4 class="globleHeadingh4 globlegreen">4. Third Party</h4>
          <p><strong>A. Advertisements and Service Providers -</strong> The Company may use Third-party ad servers or ad networks to advertise on behalf of the Company. Your non-personal information may be obtained from such Third Party ad servers. Similarly, Third Party Advertisers may serve advertisements on the Site. These third-party ad servers or ad networks may automatically receive your IP address when they serve ads to your Internet browser. We do not provide any personally identifiable information to these third-parties without your consent. However, please note that if an advertiser asks the Company to show an advertisement to a certain audience and you respond to that advertisement, the advertiser or ad-server may conclude that you fit the description of the audience they are trying to reach. This Privacy Policy does not apply to, and we cannot control the activities of, third-party advertisers.</p>
          <p><strong>B. Access From Social Media Or Communication Platforms -</strong> You may access the Website from your social media or communications platforms. In such cases, the Company may obtain such information from the Platforms which you have authorized such Platforms to share. Without prejudiced to generality of the Clauses above, when you access the Website through such Platforms, you grant your consent to the Company to obtain, collect, store, utilize and retain such information.</p>
          <p><strong>C. Log Files -</strong> Like most standard web Site/App servers we use log files. This includes IP (internet protocol) addresses, browser type, ISP (internet service provider), referring / exit pages, platform type, date / time stamp and number of clicks to analyze trends, administer the site, track user's movement in the aggregate, and gather broad demographic information for aggregate use. IP addresses, etc. are not linked to personally identifiable information. The same may be used to track the behavior of the customers or identify the area of interest of the customer, which might further be useful for advertisement, promotions etc.</p>
          <p><strong>D. Cookies -</strong> When you visit Poker Sports League, cookies may be left in your computer. A cookie is a small text file that uniquely identifies your browser. The cookies assigned by the servers of Poker Sports League may be used to personalize your experience on Poker Sports League. Moreover, cookies may also be used for authentication, game management and security purposes. Cookies may also be assigned by the advertisers of Poker Sports League when you click on any of the advertisements which may be displayed on Poker Sports League in which case such cookies are controlled by these advertisers and not Poker Sports League.</p>
      </div>
      <div class="col-xs-12">
          <h4 class="globleHeadingh4 globlegreen">5. Purpose of Collection</h4>
          <p>The Information collected, stored and retained by the Company is used to facilitate the performance of its functions and conduct the business. The said information is also used to consider and reply to your queries, provide information to you about the services,  recognize you when you return to the Website, enhance its Service on a number of pages of the Site, protect the Site, take action qua fraud or illegal acts, serve legal Notice or Orders, perform research and data analysis, improve usability of the site, administer mailing lists or online communities or surveys, to measure the effectiveness of advertisements, to personalize the advertising content, to assist any acquisition or merger prospect of the Company, or other activities related to the services provided by the Site.</p>
      </div>
      <div class="col-xs-12">
          <h4 class="globleHeadingh4 globlegreen">6. How 'Poker Sports League' uses the collected information</h4>
          <ol class="ordrLst">
            <li>When you register your email address on the Website, you agree to receive email communication from the Company and the entities specifically authorized by the Company and other users.</li>
            <li>The Company may also use software applications for website traffic analysis and to gather statistics, used for advertising and for determining the efficacy and popularity of the Website and the league among others. </li>
            <li>The data which is transmitted over the Internet is intrinsically exposed to security risks or threats. For instance, information transmitted via chat or email can be compromised and used by others. Therefore, Poker Sports League cannot guarantee any security for such information.</li>
            <li>When you register with Poker Sports League, your account is protected by means of login information which includes a username and a password that is known only to you. Therefore, you are responsible for maintaining the confidentiality of your login information including your username and password. Poker Sports League is not responsible for any activity which is undertaken when your password is used. We suggest you not to disclose your password to anyone. If you become aware of or reasonably suspect any breach of security, including compromise of your login information, it is your responsibility to immediately notify Poker Sports League.</li>
            <li>The Website may contain links to other sites. Such websites are governed by their own privacy policies and the Company does not exercise any control over them. It is your responsibility to read and understand the privacy policy of such websites when you follow a link outside Website.</li>
          </ol>
      </div>
      <div class="col-xs-12">
          <h4 class="globleHeadingh4 globlegreen">7. Disclosure of Information</h4>
          <ol class="ordrLst">
          <li>The Company has a policy of not sharing any personally identifiable information with anyone other than entities specifically authorized by the Company which may include advertisers and sponsors of Poker Sports League. However, The Company may use your name, Login ID and the state from where you are participating when announcing the results of any contests run on the Website. Such contests are further governed by the Terms and Conditions which shall be available on the website as and when such a contest is run on the website.</li>
          <li>The Company conducts periodic analysis and survey of the traffic on the Website for market research and advertising purposes. The Company reserves the right to share your registration information with the Company appointed market research and advertising companies or firms from time to time for the said purposes. The Company may also use cumulative non-personal information for auditing and analysis purposes with the aim of improving its services.</li>
          <li>Additionally, the Company may share personally identifiable information if sharing of such information is necessary to comply with legal processes or governmental request, or to enforce the Terms of Use and this Privacy Policy, or for prevention of fraud, or for issues involving information security, or to protect your rights or the rights of Poker Sports League or the rights of the general public.</li>
          <li>Available log records and all data stored on our servers may be accessed by our system administrators. </li>
          <li>We may partner with other companies or organisations to provide you with additional services related to the Company. When you purchase or otherwise express interest in a service offered by a third party through the Company or sponsored on the Site, you consent to our sharing your information with those parties. Participation in rewards programs, discount offers, contests, or other programs that involve third parties, authorizes the Company to share your personal information with those parties. A third party’s use of your information is bound by contracts and agreements between the Company and the third party. We only share information reasonably needed to provide additional services, and such shared information may be bound by other privacy agreements. By sharing this information, you agree that the Company is not liable or responsible for the actions or inactions of third parties.</li>
          <li>We may share non-personally identifiable information (such as referring/exit pages, anonymous usage data, and URLs, platform types, number of clicks, etc.) with interested third parties to help them understand and utilize the usage patterns for certain services.</li>
          </ol>
          </div>
          <div class="col-xs-12">
          <h4 class="globleHeadingh4 globlegreen">8. Merger and other events requiring transfer</h4>
          <p>If the Company should ever file for bankruptcy, or become insolvent, or be acquired by a third party, merge with a third party, sell all or part of its assets, or transfer substantially all or part of its relevant assets to a third party, We are entitled to share the Personal Information and all other information You have provided through the Services to potential and subsequent business and merger partners.</p>
          </div>
          <div class="col-xs-12">
          <h4 class="globleHeadingh4 globlegreen">9. Age Limitation</h4>
          <p>The Services are not intended for or directed at persons under the age of twenty-one (21). Any person who informs us that his age is twenty-one (21) years or above, it is our policy to uncover the services which may require us to access and verify the person's Personal Information. If we become aware that a minor has attempted to or has submitted personal information via the Services, We will not accept this information and will take steps to remove such information from our records in a secure manner.</p>
          </div>
          <div class="col-xs-12">
          <h4 class="globleHeadingh4 globlegreen">10. Consent</h4>
          <ol class="ordrLst">
            <li>By using this Website, it is understood that you have given your consent to the collection and use of this information by Poker Sports League and its partners and affiliates.</li>
            <li>In order to play real money games, you will be required to send money to and receive money from us. We may use third-party electronic payment processors and/or financial institutions ('ESPs') to process such financial transactions. By accepting this Privacy Policy, You expressly consent to Personal Information necessary for the processing of transactions being shared with ESPs. We take steps to ensure that our arrangements with ESPs protect your privacy.</li>
            <li>We reserve the right to conduct a security review at any time to validate Your identity, age, the registration data provided by You and to verify Your use of the Services and Your financial transactions for potential breach of Our Terms and Conditions of Use and of applicable law. By using our website, you authorize Us, Our staff, agents and suppliers to use Your Personal Information and to disclose Your Personal Information to third parties for the purposes of validating the information you provide to us.</li>
            <li>By filling your mobile number on our site, you are giving Mind Sports League Pvt. Ltd. the right to contact you by Call/SMS to provide you information on all promotional activity/events conducted by Poker Sports League and its partners. Your mobile number will not be used for any third party communication whatsoever.</li>
          </ol>
          </div>
          <div class="col-xs-12">
          <h4 class="globleHeadingh4 globlegreen">11. Security</h4>
          <ol class="ordrLst">
            <li>The Site’s primary goal in collecting personal information is to provide you with a fulfilling experience. The information collected by the Site is protected by the use of appropriate technical and security measures such internal reviews of the Data collection and retention and processing procedures. The Company may use appropriate encryption and physical checks to prevent unauthorized or unlawful access to the system which contains your Information. However, the Company shall not be liable to you in the event of any unauthorized use or unauthorized access including by way of hacking or otherwise by a third party which results in any loss of data or misuse of the information contained in the site.</li>
            <li>If you make use of the payment Gateway on the Website to make the payment to the Company, you Credit Card and/or Debit Card Data shall be stored in compliance with industry standard /recommended date security standard for security of financial information. However, the security measures of such information shall be governed in accordance with the privacy policy of such ESP Service providers. </li>
            <li>As agreed, the Company may disclose your Information to other Third Parties as per the present Policy. However, the Company shall not be responsible in any manner for a breach, act or omission of the Third Party resulting in an injury to you or a person related to you.</li>
          </ol>
          </div>
          <div class="col-xs-12">
          <h4 class="globleHeadingh4 globlegreen">12. Grievance Officer</h4>
          <p>In case any Grievance or Concerns pertaining to any issue dealt with in the present Policy, please contact the grievance redressal officer as specified in the Terms of Use or on the Site. </p>
          </div>
       </div>
  </div>
</section>
<?php $this->load->view('footer');?>
<script src="<?php echo JS_PATH?>/jquery.min.js"></script>
<script src="<?php echo JS_PATH?>/owl.carousel.js"></script>
<script src="<?php echo JS_PATH?>/main.js"></script>
</body>
</html>

